COMPONENT_TYPE=PIC_PEIM

C_TYPE = PIC_PEIM PE32_PEIM

ifneq (,$(findstring $(COMPONENT_TYPE), $(C_TYPE)))
$(info find $(COMPONENT_TYPE)) 
else
$(info no find $(COMPONENT_TYPE)) 
endif

all: 
	@echo done
