a/b/c.Txt: a.txt
	@echo $@
	@echo $(patsubst %.txt,%.xyz,$@)
	@echo $?
	@echo $%
	@echo $<
	@echo $^
	@echo $+
	@echo $|
	@echo $*
	@echo at----D $(@D)
	@echo at----F $(@F)
	@echo x-----D $(*D)
	@echo x-----F $(*F)
	@echo bai---D $(%D)
	@echo bai---F $(%F)
	@echo xiao--D $(<D)
	@echo xiao--F $(<F)
	@echo p-----D $(^D)
	@echo p-----F $(^F)
	@echo add---D $(+D)
	@echo add---F $(+F)
	@echo w-----D $(?D)
	@echo w-----F $(?F)
